import { parseZip } from './zip.js';
import { defaultSettings, loadHomeState, loadSettings, migrateLegacyData, openDatabase, read, remove, saveHomeState, saveSettings, STORES, write } from './core/storage.js';
import { createWebsite, deleteProject, getProject, listProjects, mimeFor, newId, normalizeURL, projectURL, refreshWebsiteIcon, sanitizePath, saveProject, saveProjectFiles } from './core/projects.js';
import { createHomeController } from './ui/home.js';
import { gradient, renderIcon } from './ui/icons.js';
import { openIconDesigner } from './ui/icon-designer.js';
import { applyGlassMaterial } from './core/glass.js';
import { applyFrameMaterial } from './core/frame.js';

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const el = Object.fromEntries(['workspace','homeScreen','homeAppGrid','homeDock','homeEditDone','widgetArea','wallpaper','statusTime','workspaceViewButton','homeViewButton','settingsButton','runtimeOrb','runtimeStatus','runtimeDetail','importFileButton','importFolderButton','importZipButton','filePicker','folderPicker','zipPicker','projectSearch','projectCount','projectGrid','emptyLibrary','capabilityGrid','activityButton','diagnosticsDialog','closeDiagnostics','consoleLog','networkLog','performancePanel','clearConsole','clearNetwork','viewer','projectFrame','viewerProjectName','viewerProjectPath','viewerControl','viewerMenu','viewerReload','viewerBrowser','viewerHome','viewerWorkspace','projectDialog','projectDialogTitle','projectNameInput','projectTrustSelect','projectSpaSelect','projectCompatToggle','projectDebugToggle','projectDockToggle','projectIconPreview','saveProjectButton','deleteProjectButton','updateProjectButton','chooseIconButton','clearIconButton','iconPicker','entryDialog','entryList','toastHost','settingsDialog','startViewSelect','iconLabelsToggle','wallpaperDimRange','glassStyleSelect','glassIntensityRange','glassIntensityValue','frameStyleSelect','clockWidgetToggle','calendarWidgetToggle','defaultCompatToggle','defaultDebugToggle','wallpaperPresets','customWallpaperButton','wallpaperPicker','storageSummary','clearAllButton','versionLabel'].map((id) => [id, document.getElementById(id)]));
const wallpaper = [{ id: 'graphite', css: 'radial-gradient(circle at 24% 16%, #737987 0%, #343942 26%, #15181e 62%, #08090b 100%)' }, { id: 'ocean', css: 'radial-gradient(circle at 22% 8%, #6aa7bf 0%, #376a81 22%, #19384a 48%, #0b1722 100%)' }, { id: 'forest', css: 'radial-gradient(circle at 18% 4%, #7da58b 0%, #466751 25%, #20342c 52%, #0b1410 100%)' }];
let projects = []; let settings = { ...defaultSettings }; let editingId = null; let updateId = null; let activeId = null; let home;

function toast(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; el.toastHost.append(node); setTimeout(() => node.remove(), 2600); }
function status(kind, title, detail) { el.runtimeOrb.className = `status-orb ${kind || ''}`; el.runtimeStatus.textContent = title; el.runtimeDetail.textContent = detail; }
function bytes(value) { if (!Number.isFinite(value)) return '—'; return value < 1024 ? `${value} B` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
function currentProject(id) { return projects.find((project) => project.id === id); }
function renderCapabilities() { const capabilities = [['Service worker', 'serviceWorker' in navigator], ['IndexedDB', 'indexedDB' in window], ['Folder import', 'webkitdirectory' in el.folderPicker], ['ZIP / DEFLATE', 'DecompressionStream' in window], ['WebCrypto', Boolean(crypto.subtle)], ['Wake Lock', 'wakeLock' in navigator]]; el.capabilityGrid.replaceChildren(...capabilities.map(([name, available]) => { const node = document.createElement('div'); node.className = 'capability'; node.innerHTML = `<span>${name}</span><strong class="${available ? 'yes' : 'partial'}">${available ? 'Available' : 'Unavailable'}</strong>`; return node; })); }
async function updateStorageSummary() { const imported = projects.reduce((total, project) => total + (project.totalBytes || 0), 0); let text = `${projects.length} ${projects.length === 1 ? 'project' : 'projects'} · ${bytes(imported)} imported content.`; try { const estimate = await navigator.storage?.estimate?.(); if (estimate?.usage != null) text += ` Browser origin: ${bytes(estimate.usage)} used of approximately ${bytes(estimate.quota)}.`; } catch {} el.storageSummary.textContent = text; }
function openDiagnostics() { el.consoleLog.textContent = 'No runtime errors captured.'; el.networkLog.textContent = 'No network events captured.'; el.diagnosticsDialog.showModal(); }

async function refresh() { projects = await listProjects(); renderLibrary(); await renderHome(); }
function renderLibrary() { const query = el.projectSearch.value.trim().toLowerCase(); const visible = projects.filter((project) => !query || `${project.name} ${project.sourceName || ''}`.toLowerCase().includes(query)); el.projectCount.textContent = String(projects.length); el.emptyLibrary.classList.toggle('hidden', projects.length > 0); el.projectGrid.replaceChildren(); for (const project of visible) { const card = document.createElement('article'); card.className = 'project-card'; card.dataset.id = project.id; const head = document.createElement('div'); head.className = 'project-card-head'; const icon = document.createElement('div'); icon.className = 'app-icon'; void renderIcon(icon, project); const copy = document.createElement('div'); copy.className = 'project-card-copy'; copy.innerHTML = `<strong></strong><small></small>`; copy.querySelector('strong').textContent = project.name; copy.querySelector('small').textContent = project.type === 'website' ? project.externalUrl : `${project.fileCount || 0} files · ${bytes(project.totalBytes || 0)}`; head.append(icon, copy); const actions = document.createElement('div'); actions.className = 'project-actions'; const open = document.createElement('button'); open.className = 'primary-mini'; open.textContent = 'Open'; open.addEventListener('click', () => openProject(project.id)); const edit = document.createElement('button'); edit.textContent = 'Settings'; edit.addEventListener('click', () => openDialog(project.id)); actions.append(open, edit); card.append(head, actions); el.projectGrid.append(card); } }
function homeItem(project) { const node = document.createElement('div'); node.className = `home-app${settings.iconLabels ? '' : ' no-label'}`; node.dataset.homeItem = 'true'; node.dataset.id = project.id; const icon = document.createElement('div'); icon.className = 'home-app-icon'; void renderIcon(icon, project); const label = document.createElement('span'); label.className = 'home-app-label'; label.textContent = project.name; const badge = document.createElement('button'); badge.className = 'app-delete-badge'; badge.type = 'button'; badge.textContent = '−'; badge.setAttribute('aria-label', 'Delete'); node.append(icon, label, badge); return node; }
function runnerItem() { const node = document.createElement('div'); node.className = `home-app${settings.iconLabels ? '' : ' no-label'}`; node.dataset.homeItem = 'true'; node.dataset.runner = 'true'; const icon = document.createElement('div'); icon.className = 'home-app-icon'; void renderIcon(icon, { id: '__runner__', name: 'Pro Runner' }); const label = document.createElement('span'); label.className = 'home-app-label'; label.textContent = 'Pro Runner'; node.append(icon, label); return node; }
function widgets() { el.widgetArea.replaceChildren(); if (settings.clockWidget) { const node = document.createElement('div'); node.className = 'home-widget clock-widget glass-surface glass-surface-panel'; node.dataset.homeItem = 'true'; node.dataset.widget = 'clock'; node.innerHTML = '<div class="clock-time"></div><div class="clock-date"></div>'; el.widgetArea.append(node); } if (settings.calendarWidget) { const node = document.createElement('div'); node.className = 'home-widget calendar-widget'; node.dataset.homeItem = 'true'; node.dataset.widget = 'calendar'; node.innerHTML = '<div class="calendar-head"><strong class="calendar-month"></strong><span class="calendar-today"></span></div><div class="mini-weekdays" aria-hidden="true"></div><div class="mini-month"></div>'; el.widgetArea.append(node); } updateClock(); }
async function renderHome() { el.homeAppGrid.replaceChildren(); el.homeDock.replaceChildren(); widgets(); el.homeAppGrid.append(runnerItem(), ...projects.map(homeItem)); if (!home) home = createHomeController({ home: el.homeScreen, content: $('.home-content'), grid: el.homeAppGrid, dock: el.homeDock, done: el.homeEditDone, load: loadHomeState, save: saveHomeState, onOpen: openProject, onEdit: openDialog, onDelete: requestDelete }); await home.render(); applyWallpaper(); applyGlass(); applyFrame(); }
function updateClock() { const now = new Date(); const time = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }); el.statusTime.textContent = time; $('.clock-time')?.replaceChildren(time); const date = $('.clock-date'); if (date) date.textContent = now.toLocaleDateString([], { weekday: 'long', month: 'long', day: 'numeric' }); const month = $('.calendar-month'); const today = $('.calendar-today'); const weekdays = $('.mini-weekdays'); const grid = $('.mini-month'); if (month && today && weekdays && grid) { month.textContent = now.toLocaleDateString([], { month: 'long' }); today.textContent = String(now.getDate()); weekdays.replaceChildren(...Array.from({ length: 7 }, (_, index) => { const day = document.createElement('span'); day.textContent = new Intl.DateTimeFormat(navigator.language || 'en', { weekday: 'narrow' }).format(new Date(2024, 0, 1 + index)); return day; })); grid.replaceChildren(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); for (let index = 0; index < offset; index += 1) { const blank = document.createElement('span'); blank.className = 'blank'; grid.append(blank); } for (let day = 1; day <= days; day += 1) { const cell = document.createElement('span'); cell.textContent = String(day); if (day === now.getDate()) cell.className = 'today'; grid.append(cell); } } }
function applyWallpaper() { const item = wallpaper.find((entry) => entry.id === settings.wallpaper) || wallpaper[0]; el.wallpaper.style.backgroundImage = item.css; document.documentElement.style.setProperty('--wallpaper-dim', String(settings.wallpaperDim / 100)); if (settings.wallpaper === 'custom') read(STORES.assets, 'wallpaper').then((asset) => { if (asset?.bytes) el.wallpaper.style.backgroundImage = `url(${URL.createObjectURL(new Blob([asset.bytes], { type: asset.type || 'image/jpeg' }))})`; }); }
function applyGlass() { const material = applyGlassMaterial(document.documentElement, { style: settings.glassStyle, intensity: settings.glassIntensity }); if (el.glassIntensityValue) el.glassIntensityValue.textContent = `${Math.round(material.intensity)}%`; }
function applyFrame() { applyFrameMaterial(document.documentElement, { style: settings.frameStyle }); }
function showHome() { el.workspace.classList.add('hidden'); el.homeScreen.classList.remove('hidden'); closeViewer(); void renderHome(); }
function showWorkspace() { el.homeScreen.classList.add('hidden'); el.workspace.classList.remove('hidden'); closeViewer(); home?.exitEdit(); }

function openProject(id) { if (id === '__runner__') { showWorkspace(); return; } const project = currentProject(id); if (!project) return; const website = project.type === 'website'; if (website && project.websiteLaunchMode === 'browser') { const opened = window.open(project.externalUrl, '_blank'); if (opened) opened.opener = null; else toast('Allow pop-ups to open this website in the browser.'); return; } if (!website && !navigator.serviceWorker?.controller) { toast('The local runtime is not ready yet.'); return; } activeId = id; el.viewerProjectName.textContent = project.name; el.viewerProjectPath.textContent = website ? new URL(project.externalUrl).hostname : project.entryPath; el.projectFrame.removeAttribute('sandbox'); el.projectFrame.allow = website ? 'clipboard-read; clipboard-write; fullscreen; web-share' : ''; el.projectFrame.src = website ? project.externalUrl : projectURL(project.id, project.entryPath); el.viewerBrowser.classList.toggle('hidden', !website); el.workspace.classList.add('hidden'); el.homeScreen.classList.add('hidden'); el.viewer.classList.remove('hidden'); }
function closeViewer() { if (!el.viewer.classList.contains('hidden')) { el.projectFrame.src = 'about:blank'; el.viewer.classList.add('hidden'); activeId = null; } }

function runnerDialog() { let dialog = document.getElementById('runnerSettingsDialog'); if (dialog) return dialog; dialog = document.createElement('dialog'); dialog.id = 'runnerSettingsDialog'; dialog.className = 'modal'; dialog.innerHTML = '<div class="modal-card"><div class="modal-head"><div><span class="eyebrow">PRO RUNNER</span><h2>Home icon</h2></div><button class="close-button" type="button">×</button></div><div class="runner-icon-editor"><div class="large-app-icon runner-icon-preview"></div><div class="runner-icon-actions"><button class="runner-design subtle-button" type="button">Design icon</button><button class="runner-image subtle-button" type="button">Choose image…</button><button class="runner-default text-button" type="button">Use default icon</button></div></div><label class="toggle-row"><span><strong>Pin to dock</strong><small>Keep the Pro Runner return icon in the Home dock.</small></span><input class="runner-dock" type="checkbox" role="switch"></label><div class="modal-actions"><button class="runner-done primary-button" type="button">Done</button></div></div>'; document.body.append(dialog); const picker = document.createElement('input'); picker.type = 'file'; picker.accept = 'image/*'; picker.className = 'visually-hidden'; document.body.append(picker); const preview = () => renderIcon(dialog.querySelector('.runner-icon-preview'), { id: '__runner__', name: 'Pro Runner' }); const saveDock = async () => { const state = await loadHomeState(); const key = 'runner'; state.dockSlots = (state.dockSlots || [null, null, null, null]).filter((item) => item !== key); while (state.dockSlots.length < 4) state.dockSlots.push(null); if (dialog.querySelector('.runner-dock').checked) { const free = state.dockSlots.indexOf(null); if (free >= 0) state.dockSlots[free] = key; else { dialog.querySelector('.runner-dock').checked = false; toast('The dock already has four items.'); } } state.dock = state.dockSlots.filter(Boolean); await saveHomeState(state); await renderHome(); }; dialog.querySelector('.close-button').onclick = () => dialog.close(); dialog.querySelector('.runner-done').onclick = async () => { await saveDock(); dialog.close(); }; dialog.querySelector('.runner-image').onclick = () => picker.click(); picker.onchange = async () => { const file = picker.files?.[0]; if (!file) return; await write(STORES.assets, { key: 'icon:__runner__', bytes: await file.arrayBuffer(), type: file.type || 'image/png', updatedAt: Date.now(), source: 'runner-upload' }); picker.value = ''; await preview(); await renderHome(); }; dialog.querySelector('.runner-default').onclick = async () => { await remove(STORES.assets, 'icon:__runner__'); await preview(); await renderHome(); }; dialog.querySelector('.runner-design').onclick = () => openIconDesigner({ project: { id: '__runner__', name: 'Pro Runner' }, onSaved: async () => { await preview(); await renderHome(); }, chooseImage: () => picker.click() }); return dialog; }
async function openDialog(id) { if (id === '__runner__') { const dialog = runnerDialog(); const state = await loadHomeState(); dialog.querySelector('.runner-dock').checked = state.dock.includes('runner'); await renderIcon(dialog.querySelector('.runner-icon-preview'), { id: '__runner__', name: 'Pro Runner' }); dialog.showModal(); return; } const project = currentProject(id); if (!project) return; editingId = id; el.projectDialogTitle.textContent = project.name; el.projectNameInput.value = project.name; el.projectDockToggle.checked = (await loadHomeState()).dock.includes(`project:${id}`); const website = project.type === 'website'; $('.field-grid', el.projectDialog).classList.toggle('hidden', website); el.projectCompatToggle.closest('.toggle-row').classList.toggle('hidden', website); el.projectDebugToggle.closest('.toggle-row').classList.toggle('hidden', website); el.updateProjectButton.classList.toggle('hidden', website); el.clearIconButton.textContent = website ? 'Use automatic icon' : 'Use default icon'; let url = $('#websiteURL', el.projectDialog); if (website && !url) { url = document.createElement('label'); url.id = 'websiteURLRow'; url.className = 'field'; url.innerHTML = '<span>Website URL</span><input id="websiteURL" type="url">'; $('.project-editor', el.projectDialog).prepend(url); } let launch = $('#websiteLaunchModeRow', el.projectDialog); if (website && !launch) { launch = document.createElement('label'); launch.id = 'websiteLaunchModeRow'; launch.className = 'field'; launch.innerHTML = '<span>Open website</span><select id="websiteLaunchMode"><option value="embedded">Inside Pro Runner</option><option value="browser">Directly in browser</option></select>'; $('#websiteURLRow', el.projectDialog).after(launch); } if (website) { $('#websiteURL').value = project.externalUrl; $('#websiteLaunchMode').value = project.websiteLaunchMode || 'embedded'; } else { $('#websiteURLRow')?.remove(); $('#websiteLaunchModeRow')?.remove(); } el.projectTrustSelect.value = project.trust || 'trusted'; el.projectSpaSelect.value = String(Boolean(project.spaFallback)); el.projectCompatToggle.checked = Boolean(project.compatibility); el.projectDebugToggle.checked = Boolean(project.debug); await renderIcon(el.projectIconPreview, project); el.projectDialog.showModal(); }
async function saveDialog() { let project = currentProject(editingId); if (!project) return; project.name = el.projectNameInput.value.trim() || project.name; if (project.type === 'website') { const previousURL = project.externalUrl; project.externalUrl = normalizeURL($('#websiteURL').value); project.websiteLaunchMode = $('#websiteLaunchMode').value; project.sourceName = project.externalUrl; project.entryPath = new URL(project.externalUrl).hostname; await saveProject(project); if (project.externalUrl !== previousURL) project = await refreshWebsiteIcon(project); } else { Object.assign(project, { trust: el.projectTrustSelect.value, spaFallback: el.projectSpaSelect.value === 'true', compatibility: el.projectCompatToggle.checked, debug: el.projectDebugToggle.checked }); await saveProject(project); } const state = await loadHomeState(); const key = `project:${project.id}`; const slots = [...(state.dockSlots || [null, null, null, null])]; const index = slots.indexOf(key); if (!el.projectDockToggle.checked && index >= 0) slots[index] = null; if (el.projectDockToggle.checked && index < 0) { const free = slots.indexOf(null); if (free >= 0) slots[free] = key; else { toast('The dock can contain up to four items.'); return; } } state.dockSlots = slots; state.dock = slots.filter(Boolean); await saveHomeState(state); el.projectDialog.close(); await refresh(); }
async function requestDelete(id = editingId) { const project = currentProject(id); if (!project || !confirm(`Delete “${project.name}” from Pro Runner?`)) return; await deleteProject(id); const state = await loadHomeState(); delete state.positions[`project:${id}`]; state.dock = state.dock.filter((entry) => entry !== `project:${id}`); await saveHomeState(state); el.projectDialog.close(); await refresh(); }

function stripRoot(entries) { const roots = entries.map((entry) => entry.path.split('/')[0]); return roots.length && roots.every((root) => root === roots[0]) && entries.every((entry) => entry.path.includes('/')) ? entries.map((entry) => ({ ...entry, path: entry.path.split('/').slice(1).join('/') })) : entries; }
async function selectEntry(records) { const candidates = records.map((record) => record.path).filter((path) => /\.x?html?$/i.test(path)); if (candidates.length <= 1) return candidates[0] || records[0]?.path; return new Promise((resolve) => { el.entryList.replaceChildren(); for (const path of candidates) { const button = document.createElement('button'); button.type = 'button'; button.textContent = path; button.addEventListener('click', () => { el.entryDialog.close(); resolve(path); }); el.entryList.append(button); } el.entryDialog.showModal(); }); }
async function importRecords(records, kind, name, existing = null) { const id = existing?.id || newId(); const clean = stripRoot(records).map((record) => ({ ...record, path: sanitizePath(record.path), projectId: id })); const entryPath = await selectEntry(clean); if (!entryPath) return; const order = Math.max(0, ...projects.map((project) => project.homeOrder || 0)) + 1; const project = { ...(existing || {}), id, type: 'local', kind, name: existing?.name || name.replace(/\.[^.]+$/, ''), sourceName: name, entryPath, fileCount: clean.length, totalBytes: clean.reduce((sum, record) => sum + record.bytes.byteLength, 0), trust: existing?.trust || 'trusted', compatibility: existing?.compatibility ?? settings.defaultCompat, debug: existing?.debug ?? settings.defaultDebug, spaFallback: existing?.spaFallback || false, importedAt: existing?.importedAt || Date.now(), homeOrder: existing?.homeOrder || order }; await saveProjectFiles(project, clean); await refresh(); toast('Project stored locally.'); }
async function fromFiles(files, kind, existing) { const items = await Promise.all([...files].map(async (file) => ({ path: file.webkitRelativePath || file.name, bytes: await file.arrayBuffer(), type: mimeFor(file.name, file.type) }))); await importRecords(items, kind, files[0]?.webkitRelativePath?.split('/')[0] || files[0]?.name || 'Web project', existing); }
async function fromZip(file, existing) { const entries = await parseZip(await file.arrayBuffer()); await importRecords(entries.map((entry) => ({ path: entry.name, bytes: entry.bytes, type: mimeFor(entry.name) })), 'zip', file.name, existing); }
function websiteDialog() { let dialog = document.getElementById('websiteShortcutDialog'); if (dialog) return dialog; dialog = document.createElement('dialog'); dialog.id = 'websiteShortcutDialog'; dialog.className = 'modal'; dialog.innerHTML = '<div class="modal-card"><div class="modal-head"><div><span class="eyebrow">ONLINE SHORTCUT</span><h2>Add website</h2></div><button class="close-button" type="button">×</button></div><label class="field"><span>Website URL</span><input id="websiteShortcutURL" type="url" inputmode="url" placeholder="https://example.com"></label><label class="field"><span>Name <small>(optional)</small></span><input id="websiteShortcutName" type="text" maxlength="80"></label><div class="modal-actions"><button class="website-cancel subtle-button" type="button">Cancel</button><button class="website-save primary-button" type="button">Add website</button></div></div>'; document.body.append(dialog); dialog.querySelector('.close-button').onclick = () => dialog.close(); dialog.querySelector('.website-cancel').onclick = () => dialog.close(); dialog.querySelector('.website-save').onclick = async () => { const button = dialog.querySelector('.website-save'); button.disabled = true; try { const project = await createWebsite({ url: dialog.querySelector('#websiteShortcutURL').value, name: dialog.querySelector('#websiteShortcutName').value, homeOrder: Math.max(0, ...projects.map((entry) => entry.homeOrder || 0)) + 1 }); dialog.close(); await refresh(); toast(`Added ${project.name}.`); } catch (error) { toast(error.message || 'Unable to add website.'); } finally { button.disabled = false; } }; return dialog; }
function addWebsite() { const dialog = websiteDialog(); dialog.querySelector('#websiteShortcutURL').value = ''; dialog.querySelector('#websiteShortcutName').value = ''; dialog.showModal(); dialog.querySelector('#websiteShortcutURL').focus(); }
async function ensureServiceWorker() {
  if (!('serviceWorker' in navigator)) throw new Error('Service workers are not supported by this browser.');
  let timeout;
  let onControllerChange;
  try {
    await Promise.race([
      (async () => {
        await navigator.serviceWorker.register('./sw.js', { scope: './', updateViaCache: 'none' });
        await navigator.serviceWorker.ready;
        if (navigator.serviceWorker.controller) return;
        await new Promise((resolve) => {
          onControllerChange = resolve;
          navigator.serviceWorker.addEventListener('controllerchange', onControllerChange);
          if (navigator.serviceWorker.controller) resolve();
        });
      })(),
      new Promise((_, reject) => { timeout = setTimeout(() => reject(new Error('The service worker did not take control of this page. Reload Pro Runner and try again.')), 10_000); }),
    ]);
  } finally {
    clearTimeout(timeout);
    if (onControllerChange) navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange);
  }
  return true;
}
function bind() {
  el.workspaceViewButton.addEventListener('click', showWorkspace); el.homeViewButton.addEventListener('click', showHome); el.settingsButton.addEventListener('click', async () => { syncSettings(); await updateStorageSummary(); el.settingsDialog.showModal(); }); el.projectSearch.addEventListener('input', renderLibrary);
  el.importFileButton.addEventListener('click', () => el.filePicker.click()); el.importFolderButton.addEventListener('click', () => el.folderPicker.click()); el.importZipButton.addEventListener('click', () => el.zipPicker.click());
  el.filePicker.addEventListener('change', async () => { if (el.filePicker.files?.[0]) await fromFiles(el.filePicker.files, 'file', updateId && currentProject(updateId)); updateId = null; el.filePicker.value = ''; }); el.folderPicker.addEventListener('change', async () => { if (el.folderPicker.files?.length) await fromFiles(el.folderPicker.files, 'folder', updateId && currentProject(updateId)); updateId = null; el.folderPicker.value = ''; }); el.zipPicker.addEventListener('change', async () => { if (el.zipPicker.files?.[0]) await fromZip(el.zipPicker.files[0], updateId && currentProject(updateId)); updateId = null; el.zipPicker.value = ''; });
  const websiteButton = document.createElement('button'); websiteButton.id = 'importWebsiteButton'; websiteButton.className = 'import-card'; websiteButton.type = 'button'; websiteButton.innerHTML = '<span class="import-icon">↗</span><span><strong>Website URL</strong><small>Add an online app shortcut</small></span>'; websiteButton.addEventListener('click', addWebsite); $('.import-row').append(websiteButton);
  const openExternalProject = () => { const project = currentProject(activeId); if (project?.type === 'website') window.open(project.externalUrl, '_blank', 'noopener,noreferrer'); }; el.viewerControl.addEventListener('click', () => el.viewerMenu.classList.toggle('hidden')); el.viewerReload.addEventListener('click', () => { const project = currentProject(activeId); if (project) openProject(project.id); }); el.viewerBrowser.addEventListener('click', openExternalProject); el.viewerHome.addEventListener('click', showHome); el.viewerWorkspace.addEventListener('click', showWorkspace);
  el.saveProjectButton.addEventListener('click', () => saveDialog().catch((error) => toast(error.message))); el.deleteProjectButton.addEventListener('click', () => requestDelete()); el.updateProjectButton.addEventListener('click', () => { const project = currentProject(editingId); updateId = project?.id || null; el.projectDialog.close(); if (project?.kind === 'folder') el.folderPicker.click(); else if (project?.kind === 'zip') el.zipPicker.click(); else el.filePicker.click(); });
  el.designIconButton = document.getElementById('designIconButton'); el.designIconButton.addEventListener('click', () => { const project = currentProject(editingId); if (project) openIconDesigner({ project, onSaved: async () => { await renderIcon(el.projectIconPreview, project); await refresh(); } }); }); el.chooseIconButton.addEventListener('click', () => el.iconPicker.click()); el.iconPicker.addEventListener('change', async () => { const file = el.iconPicker.files?.[0]; if (file && editingId) { await write(STORES.assets, { key: `icon:${editingId}`, bytes: await file.arrayBuffer(), type: file.type || 'image/png', source: 'user-image', updatedAt: Date.now() }); await renderIcon(el.projectIconPreview, currentProject(editingId)); await refresh(); } el.iconPicker.value = ''; }); el.clearIconButton.addEventListener('click', async () => { const project = currentProject(editingId); if (project?.type === 'website') await refreshWebsiteIcon(project); else if (project) await remove(STORES.assets, `icon:${editingId}`); await refresh(); });
  el.startViewSelect.addEventListener('change', saveSettingsFromUI); el.iconLabelsToggle.addEventListener('change', saveSettingsFromUI); el.wallpaperDimRange.addEventListener('input', saveSettingsFromUI); el.glassStyleSelect.addEventListener('change', saveSettingsFromUI); el.glassIntensityRange.addEventListener('input', () => { settings.glassIntensity = Number(el.glassIntensityRange.value); applyGlass(); }); el.glassIntensityRange.addEventListener('change', saveSettingsFromUI); el.frameStyleSelect.addEventListener('change', saveSettingsFromUI); el.clockWidgetToggle.addEventListener('change', saveSettingsFromUI); el.calendarWidgetToggle.addEventListener('change', saveSettingsFromUI); el.defaultCompatToggle.addEventListener('change', saveSettingsFromUI); el.defaultDebugToggle.addEventListener('change', saveSettingsFromUI);
  el.customWallpaperButton.addEventListener('click', () => el.wallpaperPicker.click()); el.wallpaperPicker.addEventListener('change', async () => { const file = el.wallpaperPicker.files?.[0]; if (!file) return; await write(STORES.assets, { key: 'wallpaper', bytes: await file.arrayBuffer(), type: file.type || 'image/jpeg' }); settings.wallpaper = 'custom'; await saveSettings(settings); applyWallpaper(); el.wallpaperPicker.value = ''; }); el.activityButton.addEventListener('click', openDiagnostics); el.closeDiagnostics.addEventListener('click', () => el.diagnosticsDialog.close()); el.clearConsole.addEventListener('click', () => { el.consoleLog.textContent = 'No runtime errors captured.'; }); el.clearNetwork.addEventListener('click', () => { el.networkLog.textContent = 'No network events captured.'; });
  el.clearAllButton.addEventListener('click', async () => { if (!confirm('Remove all locally stored Pro Runner projects and settings?')) return; const db = await openDatabase(); try { const tx = db.transaction(Object.values(STORES), 'readwrite'); Object.values(STORES).forEach((store) => tx.objectStore(store).clear()); await new Promise((resolve, reject) => { tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); } finally { db.close(); } location.reload(); });
}
function syncSettings() { el.startViewSelect.value = settings.startView; el.iconLabelsToggle.checked = settings.iconLabels; el.wallpaperDimRange.value = settings.wallpaperDim; el.glassStyleSelect.value = settings.glassStyle; el.glassIntensityRange.value = settings.glassIntensity; el.glassIntensityValue.textContent = `${settings.glassIntensity}%`; el.frameStyleSelect.value = settings.frameStyle; el.clockWidgetToggle.checked = settings.clockWidget; el.calendarWidgetToggle.checked = settings.calendarWidget; el.defaultCompatToggle.checked = settings.defaultCompat; el.defaultDebugToggle.checked = settings.defaultDebug; el.wallpaperPresets.replaceChildren(...wallpaper.map((item) => { const button = document.createElement('button'); button.type = 'button'; button.className = `wallpaper-swatch${item.id === settings.wallpaper ? ' active' : ''}`; button.style.background = item.css; button.addEventListener('click', async () => { settings.wallpaper = item.id; await saveSettings(settings); syncSettings(); applyWallpaper(); }); return button; })); }
async function saveSettingsFromUI() { settings = { ...settings, startView: el.startViewSelect.value, iconLabels: el.iconLabelsToggle.checked, wallpaperDim: Number(el.wallpaperDimRange.value), glassStyle: el.glassStyleSelect.value, glassIntensity: Number(el.glassIntensityRange.value), frameStyle: el.frameStyleSelect.value, clockWidget: el.clockWidgetToggle.checked, calendarWidget: el.calendarWidgetToggle.checked, defaultCompat: el.defaultCompatToggle.checked, defaultDebug: el.defaultDebugToggle.checked }; await saveSettings(settings); applyWallpaper(); applyGlass(); applyFrame(); if (!el.homeScreen.classList.contains('hidden')) await renderHome(); }
async function init() {
  status('', 'Starting runtime…', 'Preparing local storage.');
  await openDatabase().then((db) => db.close());
  await migrateLegacyData();
  settings = await loadSettings();
  bind();
  await refresh();
  renderCapabilities();
  await updateStorageSummary();
  el.versionLabel.textContent = 'Architecture refactor';
  setInterval(updateClock, 1000);
  if (settings.startView === 'home') showHome();
  status('', 'Starting runtime…', 'Waiting for local project hosting.');
  try {
    await ensureServiceWorker();
    el.importFileButton.disabled = false;
    el.importZipButton.disabled = false;
    el.importFolderButton.disabled = !('webkitdirectory' in el.folderPicker);
    status('ready', 'Runtime ready', 'Local storage and virtual project hosting are available.');
  } catch (error) {
    console.error(error);
    status('error', 'Local runtime unavailable', error.message || 'The service worker could not start.');
  }
}
init().catch((error) => { console.error(error); status('error', 'Runtime error', error.message); });
