const updateStyle=document.createElement('style');updateStyle.textContent=`.update-status{min-height:32px;padding:0 11px;border:1px solid rgba(102,209,158,.22);border-radius:999px;background:rgba(102,209,158,.08);color:#b9e8cf;display:inline-flex;align-items:center;gap:7px;cursor:pointer;font-size:10px;font-weight:700;white-space:nowrap}.update-status-dot{width:7px;height:7px;border-radius:50%;background:var(--ok);box-shadow:0 0 0 4px rgba(102,209,158,.08)}.software-update-card{border:1px solid var(--line);border-radius:17px;padding:14px;background:rgba(255,255,255,.025)}.software-update-versions{display:grid;grid-template-columns:1fr 1fr;gap:9px}.software-update-versions>div{min-width:0;border-radius:13px;padding:11px 12px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.055)}.software-update-versions span,.software-update-versions strong{display:block}.software-update-versions span{color:var(--muted);font-size:9px}.software-update-versions strong{margin-top:4px;font-size:13px}.software-update-status{min-height:30px;margin:12px 2px 4px;color:var(--muted);font-size:11px;line-height:1.45}.software-update-status[data-tone="available"]{color:#b9e8cf}.software-update-status[data-tone="ok"]{color:var(--ok)}.software-update-status[data-tone="error"]{color:#ff9a9a}.software-update-meta{margin:0 2px 12px;color:var(--faint);font-size:9px}.software-update-toggle{margin:0 -1px 12px;border:1px solid rgba(255,255,255,.07)!important;border-radius:13px;background:rgba(0,0,0,.08)}.software-update-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.software-update-actions .primary-button{margin-left:auto}.update-dialog-card{width:min(430px,calc(100vw - 28px));text-align:center;padding:26px 24px 22px}.update-dialog-mark{width:48px;height:48px;margin:0 auto 15px;border-radius:15px;display:grid;place-items:center;background:rgba(255,255,255,.075);box-shadow:inset 0 0 0 1px rgba(255,255,255,.09);font-size:25px;font-weight:300}.update-dialog-card h2{margin:8px 0 4px;font-size:24px;letter-spacing:-.035em}.update-dialog-version{color:var(--muted);font-size:11px}.update-dialog-copy{margin:16px 0 20px;color:var(--muted);font-size:12px;line-height:1.55}.update-dialog-actions{display:grid;gap:8px}.update-dialog-actions .text-button{margin-top:2px}.update-dialog-actions button:disabled,.software-update-actions button:disabled{opacity:.5;cursor:default}@media(max-width:620px){.update-status{width:32px;padding:0;justify-content:center}.update-status #updateStatusText{display:none}.software-update-actions{align-items:stretch}.software-update-actions .primary-button{margin-left:0;flex:1}}`;document.head.append(updateStyle);

const RELEASE = globalThis.PRO_RUNNER_RELEASE;
const META_VERSION = RELEASE.version;
const META_BUILD = RELEASE.build;
const VERSION_URL = new URL('./version.json', location.href);
const AUTO_CHECK_KEY = 'pro-runner-update-auto-check';
const SKIPPED_KEY = 'pro-runner-update-skipped';
const SNOOZE_KEY = 'pro-runner-update-snooze-until';
const LAST_CHECK_KEY = 'pro-runner-update-last-check';
const SNOOZE_MS = 24 * 60 * 60 * 1000;

const state = { registration:null, manifest:null, installedVersion:META_VERSION, waitingWorker:null, checking:false, installing:false };
const el = {};

function bindElements(){for(const id of['updateStatusButton','updateStatusText','installedVersionValue','latestVersionValue','updateCheckStatus','lastUpdateCheck','autoUpdateChecksToggle','checkUpdateButton','installUpdateButton','skipUpdateButton','updateDialog','updateDialogTitle','updateDialogCopy','updateDialogVersion','updateDialogInstall','updateDialogLater','updateDialogSkip','versionLabel','viewer'])el[id]=document.getElementById(id)}
function compareVersions(a,b){const parse=(value)=>String(value||'0').replace(/^v/i,'').split('-')[0].split('.').map((part)=>Number.parseInt(part,10)||0);const av=parse(a),bv=parse(b),length=Math.max(av.length,bv.length);for(let i=0;i<length;i+=1){const diff=(av[i]||0)-(bv[i]||0);if(diff)return Math.sign(diff)}return 0}
function formatTime(timestamp){if(!timestamp)return'Never';try{return new Date(timestamp).toLocaleString([],{dateStyle:'medium',timeStyle:'short'})}catch{return new Date(timestamp).toLocaleString()}}
function autoChecksEnabled(){const stored=localStorage.getItem(AUTO_CHECK_KEY);return stored==null?true:stored==='true'}
function isSkipped(version){return Boolean(version&&localStorage.getItem(SKIPPED_KEY)===version)}
function isSnoozed(){return Number(localStorage.getItem(SNOOZE_KEY)||0)>Date.now()}
function isStandaloneExecution(){return Boolean(window.matchMedia?.('(display-mode: standalone)').matches||window.matchMedia?.('(display-mode: fullscreen)').matches||navigator.standalone===true)}
function setCheckStatus(text,tone=''){if(!el.updateCheckStatus)return;el.updateCheckStatus.textContent=text;el.updateCheckStatus.dataset.tone=tone}
function updateAvailable(){if(state.waitingWorker)return true;if(!state.manifest?.version)return false;return compareVersions(state.manifest.version,state.installedVersion||META_VERSION)>0}
function renderWorkspaceBadge(){if(!el.updateStatusButton)return;const available=updateAvailable(),skipped=isSkipped(state.manifest?.version);el.updateStatusButton.classList.toggle('hidden',!available||skipped);if(available&&!skipped&&el.updateStatusText)el.updateStatusText.textContent=state.waitingWorker?'Update ready':`Update ${state.manifest.version}`}
function updateSettingsUI(){if(el.installedVersionValue)el.installedVersionValue.textContent=state.installedVersion||META_VERSION;if(el.latestVersionValue)el.latestVersionValue.textContent=state.manifest?.version||'Not checked';if(el.lastUpdateCheck)el.lastUpdateCheck.textContent=formatTime(Number(localStorage.getItem(LAST_CHECK_KEY)||0));if(el.autoUpdateChecksToggle)el.autoUpdateChecksToggle.checked=autoChecksEnabled();if(el.versionLabel)el.versionLabel.textContent=`v${state.installedVersion||META_VERSION}`;const available=updateAvailable(),skipped=isSkipped(state.manifest?.version);if(el.installUpdateButton){el.installUpdateButton.classList.toggle('hidden',!available);el.installUpdateButton.textContent=state.waitingWorker?'Install ready update':'Download and install'}if(el.skipUpdateButton)el.skipUpdateButton.classList.toggle('hidden',!available||skipped);renderWorkspaceBadge()}
function requestWorkerVersion(worker,timeout=700){if(!worker)return Promise.resolve(null);return new Promise((resolve)=>{const channel=new MessageChannel(),timer=setTimeout(()=>resolve(null),timeout);channel.port1.onmessage=(event)=>{clearTimeout(timer);resolve(event.data?.version||null)};try{worker.postMessage({type:'GET_VERSION'},[channel.port2])}catch{clearTimeout(timer);resolve(null)}})}
async function getRegistration(){if(!('serviceWorker'in navigator))return null;if(state.registration)return state.registration;state.registration=await navigator.serviceWorker.getRegistration('./')||await navigator.serviceWorker.ready;return state.registration}
function waitForInstalled(worker,timeout=15000){if(!worker)return Promise.reject(new Error('No update worker is available.'));if(worker.state==='installed')return Promise.resolve(worker);if(worker.state==='redundant')return Promise.reject(new Error('The update worker became unavailable.'));return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Timed out while preparing the update.')),timeout);worker.addEventListener('statechange',()=>{if(worker.state==='installed'){clearTimeout(timer);resolve(worker)}else if(worker.state==='redundant'){clearTimeout(timer);reject(new Error('The update could not be prepared.'))}})})}
async function refreshWorkerState({forceUpdate=false}={}){const registration=await getRegistration();if(!registration)return;if(forceUpdate)await registration.update();if(registration.installing)await waitForInstalled(registration.installing,12000);state.waitingWorker=registration.waiting||null;const activeVersion=await requestWorkerVersion(navigator.serviceWorker.controller||registration.active);state.installedVersion=activeVersion||META_VERSION}
async function fetchReleaseManifest(){const url=new URL(VERSION_URL);url.searchParams.set('_',String(Date.now()));const response=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Update service returned HTTP ${response.status}.`);const manifest=await response.json();if(!manifest||typeof manifest.version!=='string')throw new Error('Update metadata is invalid.');return manifest}
function showTransientStatus(message){const host=document.getElementById('toastHost');if(!host)return;const item=document.createElement('div');item.className='toast';item.textContent=message;host.append(item);setTimeout(()=>item.remove(),2400)}
async function checkForUpdates({manual=false,prompt=false}={}){if(state.checking||state.installing)return;state.checking=true;if(el.checkUpdateButton)el.checkUpdateButton.disabled=true;setCheckStatus('Checking for updates…');try{await refreshWorkerState({forceUpdate:true});state.manifest=await fetchReleaseManifest();localStorage.setItem(LAST_CHECK_KEY,String(Date.now()));await refreshWorkerState();if(updateAvailable()){const ready=Boolean(state.waitingWorker);setCheckStatus(ready?`Version ${state.manifest.version} is ready to install.`:`Version ${state.manifest.version} is available.`,'available');updateSettingsUI();if(prompt)maybeShowStartupPrompt()}else{setCheckStatus('Pro Runner is up to date.','ok');updateSettingsUI();if(manual)showTransientStatus('You are running the latest version.')}}catch(error){setCheckStatus(navigator.onLine===false?'Unable to check while offline.':(error?.message||'Update check failed.'),'error');updateSettingsUI()}finally{state.checking=false;if(el.checkUpdateButton)el.checkUpdateButton.disabled=false}}
function maybeShowStartupPrompt(){if(!isStandaloneExecution())return;if(!updateAvailable()||!state.manifest?.version)return;if(isSkipped(state.manifest.version)||isSnoozed())return;if(!el.updateDialog||el.updateDialog.open)return;if(el.viewer&&!el.viewer.classList.contains('hidden'))return;const ready=Boolean(state.waitingWorker);el.updateDialogTitle.textContent=ready?'Update ready':'Update available';el.updateDialogVersion.textContent=`Version ${state.manifest.version}`;el.updateDialogCopy.textContent=ready?'A new Pro Runner version has been downloaded and is ready. Installing it restarts the app; your local projects, icons, wallpaper, and settings are preserved.':'A new Pro Runner version is available. You can install it now or continue working and update later.';el.updateDialogInstall.textContent=ready?'Restart and update':'Update now';el.updateDialog.showModal()}
async function prepareWaitingWorker(){let registration=await getRegistration();if(!registration)throw new Error('Service workers are not available.');if(registration.waiting)return registration.waiting;setCheckStatus('Downloading and verifying update…');await registration.update();if(registration.installing)await waitForInstalled(registration.installing,20000);const started=Date.now();while(!registration.waiting&&Date.now()-started<3000){await new Promise((resolve)=>setTimeout(resolve,100));registration=await getRegistration()}if(!registration.waiting){await refreshWorkerState();if(!updateAvailable())throw new Error('No newer application shell is available yet. Try again shortly.');throw new Error('The update could not be staged. Try again shortly.')}state.waitingWorker=registration.waiting;updateSettingsUI();return registration.waiting}
async function installUpdate(){if(state.installing)return;state.installing=true;for(const button of[el.installUpdateButton,el.updateDialogInstall])if(button)button.disabled=true;try{const worker=await prepareWaitingWorker();setCheckStatus('Installing update…');if(el.updateDialogCopy)el.updateDialogCopy.textContent='Installing the update. Pro Runner will restart automatically.';const changed=new Promise((resolve,reject)=>{const finish=()=>{clearTimeout(timer);resolve()};const timer=setTimeout(()=>{navigator.serviceWorker.removeEventListener('controllerchange',finish);reject(new Error('The update did not take control. Please try again.'))},8000);navigator.serviceWorker.addEventListener('controllerchange',finish,{once:true})});worker.postMessage({type:'SKIP_WAITING'});await changed;const activeVersion=await requestWorkerVersion(navigator.serviceWorker.controller,1500);if(state.manifest?.version&&activeVersion!==state.manifest.version)throw new Error('The installed update version could not be verified.');location.reload()}catch(error){setCheckStatus(error?.message||'Update installation failed.','error');showTransientStatus(error?.message||'Update installation failed.');if(el.updateDialog?.open)el.updateDialog.close()}finally{state.installing=false;for(const button of[el.installUpdateButton,el.updateDialogInstall])if(button)button.disabled=false}}
function deferUpdate(){localStorage.setItem(SNOOZE_KEY,String(Date.now()+SNOOZE_MS));if(el.updateDialog?.open)el.updateDialog.close()}
function skipUpdate(){if(!state.manifest?.version)return;localStorage.setItem(SKIPPED_KEY,state.manifest.version);localStorage.removeItem(SNOOZE_KEY);if(el.updateDialog?.open)el.updateDialog.close();updateSettingsUI();setCheckStatus(`Version ${state.manifest.version} is skipped. You can still install it manually here.`)}
function clearSkipIfNewer(){const skipped=localStorage.getItem(SKIPPED_KEY);if(skipped&&state.manifest?.version&&compareVersions(state.manifest.version,skipped)>0)localStorage.removeItem(SKIPPED_KEY)}
function wireUI(){el.updateStatusButton?.addEventListener('click',()=>{document.getElementById('settingsButton')?.click();setTimeout(()=>document.getElementById('softwareUpdateGroup')?.scrollIntoView({behavior:'smooth',block:'center'}),80)});el.checkUpdateButton?.addEventListener('click',()=>checkForUpdates({manual:true,prompt:false}));el.installUpdateButton?.addEventListener('click',installUpdate);el.skipUpdateButton?.addEventListener('click',skipUpdate);el.updateDialogInstall?.addEventListener('click',installUpdate);el.updateDialogLater?.addEventListener('click',deferUpdate);el.updateDialogSkip?.addEventListener('click',skipUpdate);el.autoUpdateChecksToggle?.addEventListener('change',()=>{localStorage.setItem(AUTO_CHECK_KEY,String(el.autoUpdateChecksToggle.checked));if(el.autoUpdateChecksToggle.checked)checkForUpdates({manual:false,prompt:false})});window.addEventListener('online',()=>{if(autoChecksEnabled()&&Number(localStorage.getItem(LAST_CHECK_KEY)||0)<Date.now()-6*60*60*1000)checkForUpdates({manual:false,prompt:false})})}
async function initUpdater(){bindElements();wireUI();if(el.versionLabel)el.versionLabel.textContent=`v${META_VERSION}`;if(el.installedVersionValue)el.installedVersionValue.textContent=META_VERSION;if(el.autoUpdateChecksToggle)el.autoUpdateChecksToggle.checked=autoChecksEnabled();if(el.lastUpdateCheck)el.lastUpdateCheck.textContent=formatTime(Number(localStorage.getItem(LAST_CHECK_KEY)||0));try{await refreshWorkerState()}catch{}updateSettingsUI();if(autoChecksEnabled()){setTimeout(async()=>{await checkForUpdates({manual:false,prompt:false});clearSkipIfNewer();updateSettingsUI();maybeShowStartupPrompt()},900)}else setCheckStatus('Automatic update checks are off.')}
if(document.readyState==='complete')initUpdater();else window.addEventListener('load',initUpdater,{once:true});
