const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB='pro-runner-v1', STORE='assets', PROJECTS='projects';
const THEMES=[['Graphite','#444a55','#111318','#f7f7f8'],['Cobalt','#4285ff','#17275d','#fff'],['Emerald','#47bd7f','#123b2a','#fff'],['Amber','#ffb33a','#6b3714','#fff'],['Rose','#e65b79','#5b1c32','#fff'],['Violet','#9872ff','#34205d','#fff']];
const GLYPHS=[['Code','</>'],['Terminal','>_'],['AI','AI'],['Effects','FX'],['Equalizer','EQ'],['DJ','DJ'],['Database','DB'],['Interface','UI'],['API','API'],['3D','3D'],['Hash','#'],['At','@'],['Infinity','∞'],['Command','⌘'],['Spark','✦'],['Diamond','◆'],['Circle','◉'],['Target','◎'],['Triangle','△'],['Square','□'],['Plus','✚'],['Cross','×'],['Wave','≋'],['Approx','≈'],['Bolt','ϟ'],['Cloud','☁'],['Music','♫'],['Note','♪'],['Play','▶'],['Home','⌂'],['Settings','⚙'],['Refresh','↻']];
const css=document.createElement('style');css.textContent=`.icon-studio-card{width:min(620px,calc(100vw - 24px));max-height:min(82dvh,760px);overflow:hidden;display:flex;flex-direction:column;padding:0!important}.icon-studio-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:19px 20px 14px;border-bottom:1px solid var(--line)}.icon-studio-head h2{margin:4px 0 0;font-size:21px}.icon-studio-tools{display:flex;gap:8px;padding:12px 14px;border-bottom:1px solid rgba(255,255,255,.06)}.icon-studio-search{flex:1;min-width:0;border:1px solid var(--line);background:rgba(255,255,255,.045);color:var(--text);border-radius:12px;padding:9px 11px;outline:none}.icon-studio-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;padding:14px;overflow:auto;-webkit-overflow-scrolling:touch}.icon-preset{border:0;background:transparent;padding:0;cursor:pointer;text-align:center;color:var(--muted)}.icon-preset-preview{display:grid;place-items:center;width:100%;aspect-ratio:1;border-radius:25%;overflow:hidden;box-shadow:inset 0 0 0 1px rgba(255,255,255,.16),0 6px 18px rgba(0,0,0,.2)}.icon-preset-preview img{width:100%;height:100%;display:block}.icon-preset small{display:block;margin-top:5px;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.icon-studio-foot{display:flex;justify-content:space-between;gap:8px;padding:12px 14px max(12px,env(safe-area-inset-bottom));border-top:1px solid rgba(255,255,255,.06);background:rgba(12,13,15,.88)}@media(max-width:520px){.icon-studio-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.icon-studio-card{max-height:86dvh}}`;document.head.append(css);
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function getAll(store){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly'),q=t.objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}
async function get(key){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readonly'),q=t.objectStore(STORE).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}
async function put(value){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put(value);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function svg(g,t){const[,a,b,fg]=t,x=esc(g[1]),fs=x.length>2?27:x.length===2?34:42;return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient><radialGradient id="h" cx=".2" cy=".08" r=".9"><stop stop-color="#fff" stop-opacity=".22"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs><rect width="128" height="128" rx="30" fill="url(#g)"/><rect width="128" height="128" rx="30" fill="url(#h)"/><rect x="1" y="1" width="126" height="126" rx="29" fill="none" stroke="#fff" stroke-opacity=".18"/><text x="64" y="69" text-anchor="middle" dominant-baseline="middle" font-family="-apple-system,BlinkMacSystemFont,Arial,sans-serif" font-size="${fs}" font-weight="750" letter-spacing="-1.5" fill="${fg}">${x}</text></svg>`}
const data=s=>`data:image/svg+xml;charset=utf-8,${encodeURIComponent(s)}`;let active=null,wired=false;const urls=new Map();
function remember(e){const n=e.target.closest?.('.home-app[data-id],.project-card[data-id]');if(n?.dataset.id)active=n.dataset.id}
async function activeId(){if(active)return active;const name=$('#projectNameInput')?.value?.trim();if(!name)return null;const ps=await getAll(PROJECTS).catch(()=>[]);return(active=ps.find(p=>p.name===name)?.id||null)}
function dialog(){let d=$('#iconStudioDialog');if(d)return d;d=document.createElement('dialog');d.id='iconStudioDialog';d.className='modal';d.innerHTML=`<div class="modal-card icon-studio-card"><div class="icon-studio-head"><div><span class="eyebrow">ICON STUDIO</span><h2>Choose an app icon</h2></div><button id="iconStudioClose" class="close-button" type="button">×</button></div><div class="icon-studio-tools"><input id="iconStudioSearch" class="icon-studio-search" type="search" placeholder="Search built-in icons"></div><div id="iconStudioGrid" class="icon-studio-grid"></div><div class="icon-studio-foot"><span class="eyebrow">192 OFFLINE PRESETS</span><button id="iconStudioUpload" class="subtle-button" type="button">Choose image…</button></div></div>`;document.body.append(d);$('#iconStudioClose',d).onclick=()=>d.close();$('#iconStudioUpload',d).onclick=()=>{d.close();$('#iconPicker')?.click()};$('#iconStudioSearch',d).oninput=render;return d}
function render(){const d=dialog(),grid=$('#iconStudioGrid',d),q=$('#iconStudioSearch',d).value.trim().toLowerCase();grid.replaceChildren();for(const g of GLYPHS)for(const t of THEMES){const label=`${g[0]} ${t[0]}`;if(q&&!label.toLowerCase().includes(q))continue;const s=svg(g,t),b=document.createElement('button');b.type='button';b.className='icon-preset';b.innerHTML=`<span class="icon-preset-preview"><img alt="" src="${data(s)}"></span><small>${g[0]}</small>`;b.title=label;b.onclick=()=>apply(s,label);grid.append(b)}}
function setIcon(el,url,stamp=''){if(!el||stamp&&el.dataset.studio141===stamp)return;el.replaceChildren();const i=document.createElement('img');i.alt='';i.src=url;i.style.cssText='width:100%;height:100%;object-fit:cover;display:block';el.append(i);if(stamp)el.dataset.studio141=stamp}
async function apply(s,label){const id=await activeId();if(!id)return;const rec={key:`icon:${id}`,bytes:new TextEncoder().encode(s).buffer,type:'image/svg+xml',source:'studio-v141',updatedAt:Date.now(),label};await put(rec);const u=data(s),stamp=`${id}:${rec.updatedAt}`;setIcon($('#projectIconPreview'),u);for(const e of $$(`.home-app[data-id="${CSS.escape(id)}"] .home-app-icon,.project-card[data-id="${CSS.escape(id)}"] .app-icon`))setIcon(e,u,stamp);dialog().close()}
async function refresh(){const ids=new Set([...$$('.home-app[data-id]').map(e=>e.dataset.id),...$$('.project-card[data-id]').map(e=>e.dataset.id)]);for(const id of ids){const a=await get(`icon:${id}`).catch(()=>null);if(!a?.bytes||a.source!=='studio-v141')continue;const stamp=`${id}:${a.updatedAt||0}`;let u=urls.get(stamp);if(!u){u=URL.createObjectURL(new Blob([a.bytes],{type:a.type||'image/svg+xml'}));urls.set(stamp,u)}for(const e of $$(`.home-app[data-id="${CSS.escape(id)}"] .home-app-icon,.project-card[data-id="${CSS.escape(id)}"] .app-icon`))setIcon(e,u,stamp)}}
function wire(){if(!wired){wired=true;document.addEventListener('pointerdown',remember,true);document.addEventListener('click',remember,true)}const b=$('#chooseIconButton');if(b&&b.dataset.studio141!=='1'){b.dataset.studio141='1';b.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();await activeId();const d=dialog();$('#iconStudioSearch',d).value='';render();d.showModal()},true)}}
let q=false;function decorate(){wire();refresh()}const o=new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;decorate()})});o.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});decorate();
