const frame=document.getElementById('projectFrame');
const viewerMenu=document.getElementById('viewerMenu');const viewerControl=document.getElementById('viewerControl');
const css=document.createElement('style');css.textContent=`
.viewer-shell{overflow:hidden!important;overscroll-behavior:none!important}#projectFrame{pointer-events:auto!important;touch-action:auto!important;overscroll-behavior:auto!important;transform:none!important;backface-visibility:visible!important;-webkit-backface-visibility:visible!important}.viewer-menu.hidden{display:none!important;pointer-events:none!important}.viewer-control{touch-action:manipulation}.touch-diagnostic{margin-top:12px;border:1px solid rgba(255,255,255,.07);border-radius:14px;padding:10px 12px;background:rgba(255,255,255,.025);font-size:10px;color:var(--muted);line-height:1.5}.touch-diagnostic strong{display:block;color:var(--text);font-size:11px;margin-bottom:3px}.touch-diagnostic .warn{color:#e8bd70}`;document.head.append(css);
const state={touches:0,scrolls:0,cancels:0,stalls:0,loads:0,menuResets:0,last:'none',at:0,active:false,moved:false,scrolled:false,startX:0,startY:0,stallTimer:0,windowStart:performance.now(),windowTouches:0,windowScrolls:0,touchRate:0,scrollRate:0};
function resetPage(){state.touches=0;state.scrolls=0;state.cancels=0;state.stalls=0;state.last='load';state.at=performance.now();state.active=false;state.moved=false;state.scrolled=false;clearTimeout(state.stallTimer);state.windowStart=performance.now();state.windowTouches=0;state.windowScrolls=0;state.touchRate=0;state.scrollRate=0}
function sampleRates(){const now=performance.now(),elapsed=(now-state.windowStart)/1000;if(elapsed>=2){state.touchRate=state.windowTouches/elapsed;state.scrollRate=state.windowScrolls/elapsed;state.windowStart=now;state.windowTouches=0;state.windowScrolls=0}}
function mark(type){state.last=type;state.at=performance.now();sampleRates();scheduleRender()}
function dismissRunnerOverlay(){let changed=false;if(viewerMenu&&!viewerMenu.classList.contains('hidden')){viewerMenu.classList.add('hidden');changed=true}if(viewerControl?.classList.contains('menu-open')){viewerControl.classList.remove('menu-open');changed=true}if(document.activeElement===viewerControl){viewerControl.blur();changed=true}if(changed)state.menuResets++}
function armStall(){clearTimeout(state.stallTimer);state.stallTimer=setTimeout(()=>{if(state.active&&state.moved&&!state.scrolled&&document.visibilityState==='visible'){state.stalls++;mark('stall candidate')}},900)}
let renderQueued=false;function scheduleRender(){if(renderQueued)return;renderQueued=true;setTimeout(()=>{renderQueued=false;render()},220)}
function render(){sampleRates();let box=document.getElementById('v150TouchDiagnostic');const panel=document.querySelector('#performancePanel .performance-grid')?.parentElement;if(!panel)return;if(!box){document.getElementById('v141TouchDiagnostic')?.remove();box=document.createElement('div');box.id='v150TouchDiagnostic';box.className='touch-diagnostic';panel.append(box)}const age=state.at?`${((performance.now()-state.at)/1000).toFixed(1)}s ago`:'—';const warning=state.stalls?`<br><span class="warn">stall candidates ${state.stalls}</span>`:'';box.innerHTML=`<strong>Touch runtime</strong>last ${state.last} · ${age}<br>touches ${state.touches} · scrolls ${state.scrolls} · cancels ${state.cancels} · loads ${state.loads}<br>rate ${state.touchRate.toFixed(1)} touch/s · ${state.scrollRate.toFixed(1)} scroll/s · menu resets ${state.menuResets}${warning}`}
function instrument(){if(!frame)return;try{const d=frame.contentDocument,w=frame.contentWindow;if(!d||!w||d.documentElement.dataset.touch150==='1'){render();return}d.documentElement.dataset.touch150='1';const onStart=e=>{dismissRunnerOverlay();state.touches++;state.windowTouches++;state.active=true;state.moved=false;state.scrolled=false;const t=e.touches?.[0];state.startX=t?.clientX||0;state.startY=t?.clientY||0;mark('touchstart')};const onMove=e=>{if(!state.active||state.moved)return;const t=e.touches?.[0];if(!t)return;if(Math.hypot(t.clientX-state.startX,t.clientY-state.startY)>8){state.moved=true;mark('gesture move');armStall()}};const onEnd=()=>{state.touches++;state.windowTouches++;state.active=false;clearTimeout(state.stallTimer);mark('touchend')};const onCancel=()=>{state.touches++;state.windowTouches++;state.cancels++;state.active=false;clearTimeout(state.stallTimer);mark('touchcancel')};d.addEventListener('touchstart',onStart,{passive:true,capture:true});d.addEventListener('touchmove',onMove,{passive:true,capture:true});d.addEventListener('touchend',onEnd,{passive:true,capture:true});d.addEventListener('touchcancel',onCancel,{passive:true,capture:true});d.addEventListener('pointercancel',()=>{state.cancels++;mark('pointercancel')},{passive:true,capture:true});w.addEventListener('scroll',()=>{state.scrolls++;state.windowScrolls++;state.scrolled=true;clearTimeout(state.stallTimer);mark('scroll')},{passive:true,capture:true});w.addEventListener('pagehide',()=>mark('pagehide'),{passive:true});w.addEventListener('pageshow',()=>mark('pageshow'),{passive:true});}catch{}render()}
if(frame){frame.removeAttribute('scrolling');frame.addEventListener('load',()=>{state.loads++;resetPage();requestAnimationFrame(instrument);setTimeout(instrument,180)})}
document.addEventListener('visibilitychange',()=>{mark(document.hidden?'visibility-hidden':'visibility-visible')},{passive:true});window.addEventListener('pageshow',()=>{requestAnimationFrame(instrument)},{passive:true});setInterval(()=>{if(document.getElementById('diagnosticsDialog')?.open)render()},1500);render();
