const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB='pro-runner-v1',ASSETS='assets',RUNNER_KEY='icon:__runner__',SETTINGS_KEY='pro-runner-runner-app-v15';
const css=document.createElement('style');css.textContent=`
.home-screen,.home-screen *{-webkit-touch-callout:none!important;-webkit-user-select:none!important;user-select:none!important}
.home-screen img{-webkit-user-drag:none!important;user-drag:none!important;pointer-events:none}
.runner-settings-card{width:min(520px,calc(100vw - 24px))}.runner-icon-editor{display:flex;align-items:center;gap:15px;padding:14px;border:1px solid var(--line);border-radius:16px;margin:14px 0}.runner-icon-editor .large-app-icon{flex:0 0 auto}.runner-icon-actions{display:grid;gap:7px;flex:1}.runner-note{color:var(--muted);font-size:10px;line-height:1.45;margin:8px 0 0}
`;
document.head.append(css);
function readSettings(){try{return{dock:false,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return{dock:false}}}function saveSettings(v){localStorage.setItem(SETTINGS_KEY,JSON.stringify(v))}
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function getAsset(){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(ASSETS,'readonly'),q=t.objectStore(ASSETS).get(RUNNER_KEY);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}async function putAsset(v){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(ASSETS,'readwrite');t.objectStore(ASSETS).put(v);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}async function delAsset(){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(ASSETS,'readwrite');t.objectStore(ASSETS).delete(RUNNER_KEY);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}
let objectURL=null,objectStamp='';function defaultRunnerIcon(node){if(!node||node.dataset.runnerIconStamp==='default')return;node.replaceChildren();node.style.background='linear-gradient(145deg,#f4f5f7,#aeb3bc)';node.style.color='#111';const s=document.createElement('span');s.className='icon-fallback';s.textContent='</>';node.append(s);node.dataset.runnerIconStamp='default'}async function renderRunnerIcon(node){if(!node)return;const a=await getAsset().catch(()=>null);if(!a?.bytes){defaultRunnerIcon(node);return}const stamp=String(a.updatedAt||a.source||'custom');if(node.dataset.runnerIconStamp===stamp)return;if(objectURL&&objectStamp!==stamp)URL.revokeObjectURL(objectURL);if(!objectURL||objectStamp!==stamp){objectURL=URL.createObjectURL(new Blob([a.bytes],{type:a.type||'image/png'}));objectStamp=stamp}node.replaceChildren();node.style.background='transparent';const img=document.createElement('img');img.alt='';img.src=objectURL;img.draggable=false;img.style.cssText='width:100%;height:100%;object-fit:cover;display:block';node.append(img);node.dataset.runnerIconStamp=stamp}
function runnerNode(){return $$('#homeScreen .home-app').find(n=>!n.dataset.id&&$('.home-app-label',n)?.textContent?.trim()==='Pro Runner')||null}
function applyRunnerPlacement(){const node=runnerNode();if(!node)return;node.dataset.runnerApp='1';const dock=$('#homeDock'),grid=$('#homeAppGrid'),settings=readSettings();if(settings.dock){const projectCount=dock.querySelectorAll('.home-app[data-id]').length;if(projectCount<4&&node.parentElement!==dock)dock.append(node);else if(projectCount>=4&&node.parentElement===dock){grid.prepend(node);settings.dock=false;saveSettings(settings)}}else if(node.parentElement===dock)grid.prepend(node);renderRunnerIcon($('.home-app-icon',node));}
function modal(){let d=$('#runnerSettingsDialog');if(d)return d;d=document.createElement('dialog');d.id='runnerSettingsDialog';d.className='modal';d.innerHTML=`<div class="modal-card runner-settings-card"><div class="modal-head"><div><span class="eyebrow">PRO RUNNER</span><h2>Home icon</h2></div><button id="runnerSettingsClose" class="close-button" type="button">×</button></div><div class="runner-icon-editor"><div id="runnerIconPreview" class="large-app-icon"></div><div class="runner-icon-actions"><button id="runnerDesignIcon" class="subtle-button" type="button">Design icon</button><button id="runnerChooseImage" class="subtle-button" type="button">Choose image…</button><button id="runnerDefaultIcon" class="text-button" type="button">Use default icon</button></div></div><label class="toggle-row"><span><strong>Pin to dock</strong><small>Keep the Pro Runner exit icon in the Home dock. It cannot be deleted.</small></span><input id="runnerDockToggle" type="checkbox" role="switch"></label><p class="runner-note">This icon always remains available so Home mode can return to the Pro Runner workspace.</p><div class="modal-actions"><button id="runnerSettingsDone" class="primary-button" type="button">Done</button></div></div>`;document.body.append(d);$('#runnerSettingsClose',d).onclick=()=>d.close();$('#runnerSettingsDone',d).onclick=()=>d.close();
 const input=document.createElement('input');input.type='file';input.accept='image/*';input.className='visually-hidden';document.body.append(input);input.onchange=async()=>{const f=input.files?.[0];if(!f)return;const bytes=await f.arrayBuffer();await putAsset({key:RUNNER_KEY,bytes,type:f.type||'image/png',source:'runner-upload-v15',updatedAt:Date.now()});await renderRunnerIcon($('#runnerIconPreview'));applyRunnerPlacement();input.value=''};$('#runnerChooseImage',d).onclick=()=>input.click();$('#runnerDefaultIcon',d).onclick=async()=>{await delAsset();await renderRunnerIcon($('#runnerIconPreview'));applyRunnerPlacement()};$('#runnerDesignIcon',d).onclick=()=>window.ProRunnerIconDesigner?.open({id:'__runner__',assetKey:RUNNER_KEY,title:'Pro Runner',chooseImage:()=>input.click(),onSaved:()=>{renderRunnerIcon($('#runnerIconPreview'));applyRunnerPlacement();}});$('#runnerDockToggle',d).onchange=()=>{const s=readSettings();if($('#runnerDockToggle',d).checked&&$('#homeDock').querySelectorAll('.home-app[data-id]').length>=4){$('#runnerDockToggle',d).checked=false;return}s.dock=$('#runnerDockToggle',d).checked;saveSettings(s);applyRunnerPlacement()};return d}
async function openModal(){const d=modal();$('#runnerDockToggle',d).checked=readSettings().dock;await renderRunnerIcon($('#runnerIconPreview'));d.showModal()}
const home=$('#homeScreen');home?.addEventListener('contextmenu',e=>{if(e.target.closest('.home-app,.home-widget')){e.preventDefault();e.stopPropagation()}},true);home?.addEventListener('dragstart',e=>{if(e.target.closest('.home-app,.home-widget'))e.preventDefault()},true);home?.addEventListener('selectstart',e=>{if(e.target.closest('.home-app,.home-widget'))e.preventDefault()},true);
home?.addEventListener('pointerup',e=>{const r=e.target.closest?.('[data-runner-app="1"]');if(!r||!home.classList.contains('springboard-editing'))return;const dock=$('#homeDock');if(!dock)return;const rect=dock.getBoundingClientRect();if(e.clientX>=rect.left&&e.clientX<=rect.right&&e.clientY>=rect.top&&e.clientY<=rect.bottom&&dock.querySelectorAll('.home-app[data-id]').length<4){const settings=readSettings();settings.dock=true;saveSettings(settings);requestAnimationFrame(applyRunnerPlacement)}},true);
home?.addEventListener('click',e=>{const r=e.target.closest?.('[data-runner-app="1"]');if(!r)return;const editing=home.classList.contains('springboard-editing')||!$('#homeEditDone')?.classList.contains('hidden');if(editing){e.preventDefault();e.stopImmediatePropagation();openModal()}},true);
let queued=false;function decorate(){applyRunnerPlacement()}new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}).observe(home||document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});window.addEventListener('pro-runner-icon-updated',e=>{if(e.detail?.id==='__runner__')applyRunnerPlacement()});decorate();
