const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB='pro-runner-v1',PROJECTS='projects',ASSETS='assets';let webProjects=new Map(),activeId=null,refreshing=false;
const style=document.createElement('style');style.textContent=`
.import-row{grid-template-columns:repeat(4,minmax(0,1fr))!important}.web-shortcut-card .import-icon{font-size:22px}.web-shortcut-modal{width:min(560px,calc(100vw - 24px))}.web-shortcut-note{font-size:10px;color:var(--muted);line-height:1.45;margin:10px 0 0}.web-url-field{margin-top:12px}.web-project-url{margin-top:12px}.project-card[data-web-shortcut="1"] .meta-chip:nth-child(2){display:none}
@media(max-width:760px){.import-row{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
`;
document.head.append(style);
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function getAll(store){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly'),q=t.objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}async function get(store,key){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly'),q=t.objectStore(store).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}async function put(store,value){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}
function newId(){return crypto.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`}
function normalizeURL(raw){let value=String(raw||'').trim();if(!/^https?:\/\//i.test(value))value=`https://${value}`;const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw new Error('Only http and https URLs are supported.');return url.href}
function proxyURL(remote){const url=new URL('./__external_icon__',location.href);url.searchParams.set('url',remote);return url.href}
function iconCandidates(page){const u=new URL(page),origin=u.origin;return ['/apple-touch-icon.png','/apple-touch-icon-precomposed.png','/android-chrome-512x512.png','/android-chrome-192x192.png','/favicon-512x512.png','/favicon-192x192.png','/favicon.ico'].map(p=>origin+p)}
function probe(remote){return new Promise(resolve=>{const img=new Image();let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);img.onload=img.onerror=null;resolve(v)};const timer=setTimeout(()=>finish(null),1800);img.onload=()=>finish({remote,width:img.naturalWidth||0,height:img.naturalHeight||0});img.onerror=()=>finish(null);img.src=proxyURL(remote)})}
async function discoverIcon(page){const results=await Promise.all(iconCandidates(page).map(probe));return results.filter(Boolean).sort((a,b)=>(b.width*b.height)-(a.width*a.height))[0]?.remote||null}
async function refreshMaps(){if(refreshing)return;refreshing=true;try{const all=await getAll(PROJECTS);webProjects=new Map(all.filter(p=>p.kind==='web'&&p.externalUrl).map(p=>[p.id,p]));}finally{refreshing=false}}
function addImportCard(){const row=$('.import-row');if(!row||$('#importWebButton'))return;const b=document.createElement('button');b.id='importWebButton';b.className='import-card web-shortcut-card';b.type='button';b.innerHTML='<span class="import-icon">↗</span><span><strong>Website URL</strong><small>Add an online app or site shortcut</small></span>';b.onclick=()=>openAddDialog();row.append(b)}
function addDialog(){let d=$('#webShortcutDialog');if(d)return d;d=document.createElement('dialog');d.id='webShortcutDialog';d.className='modal';d.innerHTML=`<div class="modal-card web-shortcut-modal"><div class="modal-head"><div><span class="eyebrow">ONLINE SHORTCUT</span><h2>Add website</h2></div><button id="webShortcutClose" class="close-button" type="button">×</button></div><label class="field"><span>Website URL</span><input id="webShortcutURL" type="url" inputmode="url" autocomplete="url" placeholder="https://example.com"></label><label class="field web-url-field"><span>Name <small>(optional)</small></span><input id="webShortcutName" type="text" maxlength="80" placeholder="Use hostname"></label><p class="web-shortcut-note">Online shortcuts open the live website. Pro Runner tries common high-resolution favicon locations and caches the best one when available; you can replace it in Icon Designer at any time.</p><div class="modal-actions"><button id="webShortcutCancel" class="subtle-button" type="button">Cancel</button><button id="webShortcutAdd" class="primary-button" type="button">Add website</button></div></div>`;document.body.append(d);$('#webShortcutClose',d).onclick=()=>d.close();$('#webShortcutCancel',d).onclick=()=>d.close();$('#webShortcutAdd',d).onclick=saveWebsite;return d}
function openAddDialog(){const d=addDialog();$('#webShortcutURL',d).value='';$('#webShortcutName',d).value='';d.showModal();setTimeout(()=>$('#webShortcutURL',d).focus(),80)}
async function saveWebsite(){const d=addDialog(),button=$('#webShortcutAdd',d);let url;try{url=normalizeURL($('#webShortcutURL',d).value)}catch{ $('#webShortcutURL',d).focus();return }button.disabled=true;button.textContent='Adding…';try{const parsed=new URL(url),icon=await discoverIcon(url);const name=$('#webShortcutName',d).value.trim()||parsed.hostname.replace(/^www\./,'');const project={id:newId(),name,customName:Boolean($('#webShortcutName',d).value.trim()),sourceName:url,kind:'web',fileCount:0,totalBytes:0,entryPath:parsed.hostname,trust:'external',spaFallback:false,compatibility:false,debug:false,dock:false,externalUrl:url,remoteIconUrl:icon,createdAt:Date.now(),updatedAt:Date.now()};await put(PROJECTS,project);d.close();location.reload()}finally{button.disabled=false;button.textContent='Add website'}}
function launch(project){try{const opened=window.open(project.externalUrl,'_blank','noopener,noreferrer');if(!opened)location.href=project.externalUrl}catch{location.href=project.externalUrl}}
async function hasCustomIcon(id){return Boolean(await get(ASSETS,`icon:${id}`).catch(()=>null))}
function setRemoteIcon(node,project){if(!node||!project.remoteIconUrl||node.dataset.remoteIconUrl===project.remoteIconUrl)return;const img=document.createElement('img');img.alt='';img.draggable=false;img.src=proxyURL(project.remoteIconUrl);img.style.cssText='width:100%;height:100%;object-fit:cover;display:block';img.onerror=()=>{img.remove();delete node.dataset.remoteIconUrl};node.replaceChildren(img);node.style.background='linear-gradient(145deg,#30343b,#101216)';node.dataset.remoteIconUrl=project.remoteIconUrl}
async function decorateRemoteIcons(){for(const [id,p] of webProjects){if(await hasCustomIcon(id))continue;for(const node of $$(`.home-app[data-id="${CSS.escape(id)}"] .home-app-icon,.project-card[data-id="${CSS.escape(id)}"] .app-icon`))setRemoteIcon(node,p);const dialog=$('#projectDialog');if(dialog?.open&&activeId===id)setRemoteIcon($('#projectIconPreview'),p);for(const card of $$(`.project-card[data-id="${CSS.escape(id)}"]`)){card.dataset.webShortcut='1';const chips=$$('.meta-chip',card);if(chips[0])chips[0].textContent='WEB';}}
}
function decorateProjectDialog(){const d=$('#projectDialog');if(!d?.open||!activeId)return;const p=webProjects.get(activeId);let row=$('#webProjectURLRow',d);if(!p){row?.remove();const fieldGrid=$('.field-grid',d);if(fieldGrid)fieldGrid.style.removeProperty('display');for(const toggle of [$('#projectCompatToggle',d),$('#projectDebugToggle',d)])toggle?.closest('.toggle-row')?.style.removeProperty('display');const update=$('#updateProjectButton',d);if(update)update.style.removeProperty('display');const clear=$('#clearIconButton',d);if(clear)clear.textContent='Use automatic icon';return}if(!row){row=document.createElement('label');row.id='webProjectURLRow';row.className='field web-project-url';row.innerHTML='<span>Website URL</span><input id="webProjectURLInput" type="url" inputmode="url">';$('.project-editor',d)?.prepend(row)}$('#webProjectURLInput',d).value=p.externalUrl;const fieldGrid=$('.field-grid',d);if(fieldGrid)fieldGrid.style.display='none';for(const toggle of [$('#projectCompatToggle',d),$('#projectDebugToggle',d)])toggle?.closest('.toggle-row')?.style.setProperty('display','none');const update=$('#updateProjectButton',d);if(update)update.style.display='none';const clear=$('#clearIconButton',d);if(clear)clear.textContent='Use website icon'}
async function saveWebSettingsCapture(event){if(!activeId||!webProjects.has(activeId))return;event.preventDefault();event.stopImmediatePropagation();const p=webProjects.get(activeId);let url;try{url=normalizeURL($('#webProjectURLInput')?.value||p.externalUrl)}catch{return}const projects=await getAll(PROJECTS),wantsDock=$('#projectDockToggle')?.checked;const otherDocked=projects.filter(x=>x.id!==p.id&&x.dock).length;if(wantsDock&&otherDocked>=4)return;const urlChanged=url!==p.externalUrl;p.name=$('#projectNameInput')?.value.trim()||p.name;p.customName=true;p.externalUrl=url;p.sourceName=url;p.entryPath=new URL(url).hostname;p.dock=Boolean(wantsDock);p.updatedAt=Date.now();if(urlChanged)p.remoteIconUrl=await discoverIcon(url);await put(PROJECTS,p);$('#projectDialog')?.close();location.reload()}
function remember(event){const card=event.target.closest?.('.project-card[data-id],.home-app[data-id]');if(card?.dataset.id)activeId=card.dataset.id}
document.addEventListener('pointerdown',remember,true);document.addEventListener('click',event=>{remember(event);const home=event.target.closest?.('.home-app[data-id]');if(home&&webProjects.has(home.dataset.id)){event.preventDefault();event.stopImmediatePropagation();launch(webProjects.get(home.dataset.id));return}const card=event.target.closest?.('.project-card[data-id]');if(card&&webProjects.has(card.dataset.id)&&event.target.closest('.primary-mini')){event.preventDefault();event.stopImmediatePropagation();launch(webProjects.get(card.dataset.id));}},true);$('#saveProjectButton')?.addEventListener('click',saveWebSettingsCapture,true);
let queued=false;async function decorate(){addImportCard();decorateProjectDialog();await decorateRemoteIcons()}new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','open']});await refreshMaps();decorate();
