const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const DB='pro-runner-v1',PROJECTS='projects',ASSETS='assets',LAYOUT_KEY='pro-runner-home-layout-v2';
let webProjects=new Map(),activeId=null,activeWebViewId=null,refreshing=false;
const style=document.createElement('style');style.textContent=`
.import-row{grid-template-columns:repeat(4,minmax(0,1fr))!important}.web-shortcut-card .import-icon{font-size:22px}.web-shortcut-modal{width:min(560px,calc(100vw - 24px))}.web-shortcut-note{font-size:10px;color:var(--muted);line-height:1.45;margin:10px 0 0}.web-url-field{margin-top:12px}.web-project-url{margin-top:12px}.project-card[data-web-shortcut="1"] .meta-chip:nth-child(2){display:none}.external-browser-button.hidden{display:none!important}
@media(max-width:760px){.import-row{grid-template-columns:repeat(2,minmax(0,1fr))!important}}
`;document.head.append(style);
function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function getAll(store){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly'),q=t.objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}
async function get(store,key){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readonly'),q=t.objectStore(store).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error);t.oncomplete=()=>db.close()})}
async function put(store,value){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).put(value);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}
async function del(store,key){const db=await openDB();return new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).delete(key);t.oncomplete=()=>{db.close();res()};t.onerror=()=>{db.close();rej(t.error)}})}
function newId(){return crypto.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`}
function normalizeURL(raw){let value=String(raw||'').trim();if(!/^https?:\/\//i.test(value))value=`https://${value}`;const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw new Error('Only http and https URLs are supported.');return url.href}
function iconCandidates(page){const u=new URL(page),origin=u.origin;return [
  '/apple-touch-icon.png','/apple-touch-icon-precomposed.png','/android-chrome-512x512.png','/android-chrome-192x192.png',
  '/icon-512.png','/icon-192.png','/icons/icon-512.png','/icons/icon-192.png','/favicon-512x512.png','/favicon-192x192.png',
  '/favicon-96x96.png','/favicon-64x64.png','/favicon-48x48.png','/favicon-32x32.png','/favicon.png','/favicon.ico'
].map(p=>origin+p)}
function probe(remote){return new Promise(resolve=>{const img=new Image();let done=false;const finish=v=>{if(done)return;done=true;clearTimeout(timer);img.onload=img.onerror=null;img.src='';resolve(v)};const timer=setTimeout(()=>finish(null),2600);img.decoding='async';img.referrerPolicy='no-referrer';img.onload=()=>finish({remote,width:img.naturalWidth||0,height:img.naturalHeight||0});img.onerror=()=>finish(null);img.src=remote})}
async function discoverIcon(page){const candidates=iconCandidates(page);const results=await Promise.all(candidates.map(probe));return results.filter(Boolean).sort((a,b)=>((b.width*b.height)-(a.width*a.height))||candidates.indexOf(a.remote)-candidates.indexOf(b.remote))[0]?.remote||null}
async function refreshMaps(){if(refreshing)return;refreshing=true;try{const all=await getAll(PROJECTS);webProjects=new Map(all.filter(p=>p.kind==='web'&&p.externalUrl).map(p=>[p.id,p]));}finally{refreshing=false}}
async function repairMissingIcons(){let changed=false;for(const p of webProjects.values()){if(p.remoteIconUrl)continue;const icon=await discoverIcon(p.externalUrl).catch(()=>null);if(!icon)continue;p.remoteIconUrl=icon;p.updatedAt=Date.now();await put(PROJECTS,p);changed=true}if(changed)await refreshMaps()}
function addImportCard(){const row=$('.import-row');if(!row||$('#importWebButton'))return;const b=document.createElement('button');b.id='importWebButton';b.className='import-card web-shortcut-card';b.type='button';b.innerHTML='<span class="import-icon">↗</span><span><strong>Website URL</strong><small>Add an online app or site shortcut</small></span>';b.onclick=()=>openAddDialog();row.append(b)}
function addDialog(){let d=$('#webShortcutDialog');if(d)return d;d=document.createElement('dialog');d.id='webShortcutDialog';d.className='modal';d.innerHTML=`<div class="modal-card web-shortcut-modal"><div class="modal-head"><div><span class="eyebrow">ONLINE SHORTCUT</span><h2>Add website</h2></div><button id="webShortcutClose" class="close-button" type="button">×</button></div><label class="field"><span>Website URL</span><input id="webShortcutURL" type="url" inputmode="url" autocomplete="url" placeholder="https://example.com"></label><label class="field web-url-field"><span>Name <small>(optional)</small></span><input id="webShortcutName" type="text" maxlength="80" placeholder="Use hostname"></label><p class="web-shortcut-note">Online shortcuts open inside Pro Runner when the website allows embedding. A browser fallback remains available. Pro Runner probes common high-resolution app-icon locations and uses the largest icon it can load.</p><div class="modal-actions"><button id="webShortcutCancel" class="subtle-button" type="button">Cancel</button><button id="webShortcutAdd" class="primary-button" type="button">Add website</button></div></div>`;document.body.append(d);$('#webShortcutClose',d).onclick=()=>d.close();$('#webShortcutCancel',d).onclick=()=>d.close();$('#webShortcutAdd',d).onclick=saveWebsite;return d}
function openAddDialog(){const d=addDialog();$('#webShortcutURL',d).value='';$('#webShortcutName',d).value='';d.showModal();setTimeout(()=>$('#webShortcutURL',d).focus(),80)}
async function saveWebsite(){const d=addDialog(),button=$('#webShortcutAdd',d);let url;try{url=normalizeURL($('#webShortcutURL',d).value)}catch{$('#webShortcutURL',d).focus();return}button.disabled=true;button.textContent='Adding…';try{const parsed=new URL(url),icon=await discoverIcon(url);const name=$('#webShortcutName',d).value.trim()||parsed.hostname.replace(/^www\./,'');const project={id:newId(),name,customName:Boolean($('#webShortcutName',d).value.trim()),sourceName:url,kind:'web',fileCount:0,totalBytes:0,entryPath:parsed.hostname,trust:'external',spaFallback:false,compatibility:false,debug:false,dock:false,externalUrl:url,remoteIconUrl:icon,createdAt:Date.now(),updatedAt:Date.now()};await put(PROJECTS,project);d.close();location.reload()}finally{button.disabled=false;button.textContent='Add website'}}
function wrapperURL(project,reload=false){const url=new URL('./external-frame.html',location.href);url.searchParams.set('url',project.externalUrl);if(reload)url.searchParams.set('_',Date.now().toString(36));return url.href}
function ensureBrowserButton(){const menu=$('#viewerMenu');if(!menu)return null;let button=$('#externalBrowserButton',menu);if(!button){button=document.createElement('button');button.id='externalBrowserButton';button.className='external-browser-button hidden';button.type='button';button.textContent='Open in browser';button.addEventListener('click',()=>{const p=webProjects.get(activeWebViewId);if(p)window.open(p.externalUrl,'_blank','noopener,noreferrer')});menu.append(button)}return button}
function launch(project){const frame=$('#projectFrame'),viewer=$('#viewer'),workspace=$('#workspace'),home=$('#homeScreen');if(!frame||!viewer)return;activeWebViewId=project.id;frame.removeAttribute('sandbox');frame.setAttribute('allow','clipboard-read; clipboard-write; fullscreen; web-share');frame.setAttribute('allowfullscreen','');frame.src=wrapperURL(project);const name=$('#viewerProjectName'),path=$('#viewerProjectPath');if(name)name.textContent=project.name;if(path)path.textContent=new URL(project.externalUrl).hostname;workspace?.classList.add('hidden');home?.classList.add('hidden');viewer.classList.remove('hidden');$('#viewerMenu')?.classList.add('hidden');$('#viewerControl')?.classList.remove('menu-open');ensureBrowserButton()?.classList.remove('hidden')}
function launchBrowser(project){window.open(project.externalUrl,'_blank','noopener,noreferrer')}
async function hasCustomIcon(id){return Boolean(await get(ASSETS,`icon:${id}`).catch(()=>null))}
function fallbackIcon(node,project){node.replaceChildren();node.style.background='linear-gradient(145deg,#30343b,#101216)';const span=document.createElement('span');span.className='icon-fallback';span.textContent=(project.name||'↗').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'↗';node.append(span)}
function setRemoteIcon(node,project){if(!node||!project.remoteIconUrl)return;const stamp=project.remoteIconUrl;if(node.dataset.remoteIconUrl===stamp&&node.querySelector('img'))return;const img=document.createElement('img');img.alt='';img.draggable=false;img.referrerPolicy='no-referrer';img.src=stamp;img.style.cssText='width:100%;height:100%;object-fit:cover;display:block';img.onerror=()=>{if(node.dataset.remoteIconUrl===stamp){delete node.dataset.remoteIconUrl;fallbackIcon(node,project)}};node.replaceChildren(img);node.style.background='#fff';node.dataset.remoteIconUrl=stamp}
async function decorateRemoteIcons(){for(const [id,p] of webProjects){if(await hasCustomIcon(id))continue;for(const node of $$(`.home-app[data-id="${CSS.escape(id)}"] .home-app-icon,.project-card[data-id="${CSS.escape(id)}"] .app-icon`))setRemoteIcon(node,p);const dialog=$('#projectDialog');if(dialog?.open&&activeId===id)setRemoteIcon($('#projectIconPreview'),p);for(const card of $$(`.project-card[data-id="${CSS.escape(id)}"]`)){card.dataset.webShortcut='1';const chips=$$('.meta-chip',card);if(chips[0])chips[0].textContent='WEB'}}}
function decorateProjectDialog(){const d=$('#projectDialog');if(!d?.open||!activeId)return;const p=webProjects.get(activeId);let row=$('#webProjectURLRow',d);if(!p){row?.remove();const fieldGrid=$('.field-grid',d);if(fieldGrid)fieldGrid.style.removeProperty('display');for(const toggle of [$('#projectCompatToggle',d),$('#projectDebugToggle',d)])toggle?.closest('.toggle-row')?.style.removeProperty('display');const update=$('#updateProjectButton',d);if(update)update.style.removeProperty('display');const clear=$('#clearIconButton',d);if(clear)clear.textContent='Use automatic icon';return}if(!row){row=document.createElement('label');row.id='webProjectURLRow';row.className='field web-project-url';row.innerHTML='<span>Website URL</span><input id="webProjectURLInput" type="url" inputmode="url">';$('.project-editor',d)?.prepend(row)}$('#webProjectURLInput',d).value=p.externalUrl;const fieldGrid=$('.field-grid',d);if(fieldGrid)fieldGrid.style.display='none';for(const toggle of [$('#projectCompatToggle',d),$('#projectDebugToggle',d)])toggle?.closest('.toggle-row')?.style.setProperty('display','none');const update=$('#updateProjectButton',d);if(update)update.style.display='none';const clear=$('#clearIconButton',d);if(clear)clear.textContent='Use website icon'}
async function saveWebSettingsCapture(event){if(!activeId||!webProjects.has(activeId))return;event.preventDefault();event.stopImmediatePropagation();const p=webProjects.get(activeId);let url;try{url=normalizeURL($('#webProjectURLInput')?.value||p.externalUrl)}catch{return}const projects=await getAll(PROJECTS),wantsDock=$('#projectDockToggle')?.checked;const otherDocked=projects.filter(x=>x.id!==p.id&&x.dock).length;if(wantsDock&&otherDocked>=4)return;const urlChanged=url!==p.externalUrl;p.name=$('#projectNameInput')?.value.trim()||p.name;p.customName=true;p.externalUrl=url;p.sourceName=url;p.entryPath=new URL(url).hostname;p.dock=Boolean(wantsDock);p.updatedAt=Date.now();if(urlChanged||!p.remoteIconUrl)p.remoteIconUrl=await discoverIcon(url);await put(PROJECTS,p);$('#projectDialog')?.close();location.reload()}
function cleanLayout(id){try{const layout=JSON.parse(localStorage.getItem(LAYOUT_KEY)||'{}');if(layout?.positions){delete layout.positions[`project:${id}`];localStorage.setItem(LAYOUT_KEY,JSON.stringify(layout))}}catch{}}
async function deleteWebsite(project){if(!project)return;const ok=confirm(`Delete the website shortcut “${project.name}”?\n\nThe website itself is not changed.`);if(!ok)return;await del(PROJECTS,project.id);await del(ASSETS,`icon:${project.id}`).catch(()=>{});cleanLayout(project.id);location.reload()}
function remember(event){const card=event.target.closest?.('.project-card[data-id],.home-app[data-id]');if(card?.dataset.id)activeId=card.dataset.id}
function isHomeEditing(){return $('#homeScreen')?.classList.contains('springboard-editing')||!$('#homeEditDone')?.classList.contains('hidden')}
document.addEventListener('pointerdown',remember,true);
document.addEventListener('click',event=>{remember(event);const badge=event.target.closest?.('.app-delete-badge');const badgeHome=badge?.closest?.('.home-app[data-id]');if(badgeHome&&webProjects.has(badgeHome.dataset.id)){event.preventDefault();event.stopImmediatePropagation();deleteWebsite(webProjects.get(badgeHome.dataset.id));return}const home=event.target.closest?.('.home-app[data-id]');if(home&&webProjects.has(home.dataset.id)){if(isHomeEditing())return;event.preventDefault();event.stopImmediatePropagation();launch(webProjects.get(home.dataset.id));return}const card=event.target.closest?.('.project-card[data-id]');if(card&&webProjects.has(card.dataset.id)&&event.target.closest('.primary-mini')){event.preventDefault();event.stopImmediatePropagation();launch(webProjects.get(card.dataset.id));}},true);
$('#saveProjectButton')?.addEventListener('click',saveWebSettingsCapture,true);
$('#deleteProjectButton')?.addEventListener('click',event=>{if(!activeId||!webProjects.has(activeId))return;event.preventDefault();event.stopImmediatePropagation();deleteWebsite(webProjects.get(activeId))},true);
$('#viewerReload')?.addEventListener('click',event=>{const p=webProjects.get(activeWebViewId);if(!p)return;event.preventDefault();event.stopImmediatePropagation();$('#projectFrame').src=wrapperURL(p,true);$('#viewerMenu')?.classList.add('hidden');$('#viewerControl')?.classList.remove('menu-open')},true);
for(const id of ['viewerHome','viewerWorkspace'])$('#'+id)?.addEventListener('click',()=>{activeWebViewId=null;ensureBrowserButton()?.classList.add('hidden')},true);
const frame=$('#projectFrame');if(frame)new MutationObserver(()=>{const src=frame.getAttribute('src')||'';const p=webProjects.get(activeWebViewId);if(!p||!src.includes('external-frame.html')){activeWebViewId=null;ensureBrowserButton()?.classList.add('hidden')}}).observe(frame,{attributes:true,attributeFilter:['src']});
let queued=false;async function decorate(){addImportCard();decorateProjectDialog();await decorateRemoteIcons()}new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','open']});
await refreshMaps();await repairMissingIcons();decorate();
