const frame=document.getElementById('projectFrame');
const viewerMenu=document.getElementById('viewerMenu');const viewerControl=document.getElementById('viewerControl');
const css=document.createElement('style');css.textContent=`
.viewer-shell{overflow:hidden!important;overscroll-behavior:auto!important;touch-action:auto!important}
#projectFrame{pointer-events:auto!important;touch-action:auto!important;overscroll-behavior:auto!important;transform:none!important;filter:none!important;backface-visibility:visible!important;-webkit-backface-visibility:visible!important}
.viewer-menu.hidden{display:none!important;pointer-events:none!important}.viewer-control{touch-action:manipulation}
.touch-diagnostic{margin-top:12px;border:1px solid rgba(255,255,255,.07);border-radius:14px;padding:10px 12px;background:rgba(255,255,255,.025);font-size:10px;color:var(--muted);line-height:1.5}.touch-diagnostic strong{display:block;color:var(--text);font-size:11px;margin-bottom:3px}.touch-diagnostic .warn{color:#e8bd70}.touch-diagnostic .ok{color:#78d6aa}`;document.head.append(css);
const state={gestures:0,ends:0,touchCancels:0,pointerCancels:0,scrolls:0,stalls:0,recoveries:0,loads:0,menuResets:0,last:'none',at:0,active:false,moved:false,scrolled:false,startX:0,startY:0,stallTimer:0,windowStart:performance.now(),windowGestures:0,windowScrolls:0,touchRate:0,scrollRate:0,cancelStreak:0,lastCancelAt:0,lastScrollAt:0,recoveryTimer:0};
function resetPage(){state.gestures=0;state.ends=0;state.touchCancels=0;state.pointerCancels=0;state.scrolls=0;state.stalls=0;state.recoveries=0;state.last='load';state.at=performance.now();state.active=false;state.moved=false;state.scrolled=false;state.cancelStreak=0;state.lastCancelAt=0;state.lastScrollAt=0;clearTimeout(state.stallTimer);clearTimeout(state.recoveryTimer);state.windowStart=performance.now();state.windowGestures=0;state.windowScrolls=0;state.touchRate=0;state.scrollRate=0}
function sampleRates(){const now=performance.now(),elapsed=(now-state.windowStart)/1000;if(elapsed>=2){state.touchRate=state.windowGestures/elapsed;state.scrollRate=state.windowScrolls/elapsed;state.windowStart=now;state.windowGestures=0;state.windowScrolls=0}}
function mark(type){state.last=type;state.at=performance.now();sampleRates();scheduleRender()}
function dismissRunnerOverlay(){let changed=false;if(viewerMenu&&!viewerMenu.classList.contains('hidden')){viewerMenu.classList.add('hidden');changed=true}if(viewerControl?.classList.contains('menu-open')){viewerControl.classList.remove('menu-open');changed=true}if(document.activeElement===viewerControl){viewerControl.blur();changed=true}if(changed)state.menuResets++}
function armStall(){clearTimeout(state.stallTimer);state.stallTimer=setTimeout(()=>{if(state.active&&state.moved&&!state.scrolled&&document.visibilityState==='visible'){state.stalls++;mark('stall candidate')}},850)}
function recoveryPulse(expectedScrollCount){clearTimeout(state.recoveryTimer);state.recoveryTimer=setTimeout(()=>{if(!frame||state.scrolls!==expectedScrollCount||document.visibilityState!=='visible')return;state.recoveries++;mark('scroll recovery');const before=frame.style.pointerEvents;frame.style.pointerEvents='none';requestAnimationFrame(()=>{frame.style.pointerEvents=before||'auto';requestAnimationFrame(()=>{try{frame.contentWindow?.focus()}catch{}})})},140)}
function noteCancelledGesture(kind){const now=performance.now();if(now-state.lastCancelAt>2600)state.cancelStreak=0;state.lastCancelAt=now;state.cancelStreak++;if(state.moved&&!state.scrolled&&state.cancelStreak>=2)recoveryPulse(state.scrolls);mark(kind)}
let renderQueued=false;function scheduleRender(){if(renderQueued)return;renderQueued=true;setTimeout(()=>{renderQueued=false;render()},180)}
function render(){sampleRates();let box=document.getElementById('v153TouchDiagnostic');const panel=document.querySelector('#performancePanel .performance-grid')?.parentElement;if(!panel)return;if(!box){document.getElementById('v150TouchDiagnostic')?.remove();document.getElementById('v141TouchDiagnostic')?.remove();box=document.createElement('div');box.id='v153TouchDiagnostic';box.className='touch-diagnostic';panel.append(box)}const age=state.at?`${((performance.now()-state.at)/1000).toFixed(1)}s ago`:'—';const warning=state.stalls?`<br><span class="warn">stall candidates ${state.stalls} · recovery pulses ${state.recoveries}</span>`:'';box.innerHTML=`<strong>Touch runtime</strong>last ${state.last} · ${age}<br>gestures ${state.gestures} · scrolls ${state.scrolls} · touch cancels ${state.touchCancels} · pointer cancels ${state.pointerCancels} · loads ${state.loads}<br>rate ${state.touchRate.toFixed(1)} gesture/s · ${state.scrollRate.toFixed(1)} scroll/s · menu resets ${state.menuResets}${warning}`}
function instrument(){if(!frame)return;try{const d=frame.contentDocument,w=frame.contentWindow;if(!d||!w||d.documentElement.dataset.touch153==='1'){render();return}d.documentElement.dataset.touch153='1';const onStart=e=>{dismissRunnerOverlay();state.gestures++;state.windowGestures++;state.active=true;state.moved=false;state.scrolled=false;const t=e.touches?.[0];state.startX=t?.clientX||0;state.startY=t?.clientY||0;mark('touchstart')};const onMove=e=>{if(!state.active||state.moved)return;const t=e.touches?.[0];if(!t)return;if(Math.hypot(t.clientX-state.startX,t.clientY-state.startY)>8){state.moved=true;mark('gesture move');armStall()}};const onEnd=()=>{state.ends++;state.active=false;clearTimeout(state.stallTimer);state.cancelStreak=0;mark('touchend')};const onTouchCancel=()=>{state.touchCancels++;const wasMoved=state.moved,wasScrolled=state.scrolled;state.active=false;clearTimeout(state.stallTimer);state.moved=wasMoved;state.scrolled=wasScrolled;noteCancelledGesture('touchcancel')};const onPointerCancel=()=>{state.pointerCancels++;mark('pointercancel')};let lastScrollStamp=0;const onScroll=()=>{const now=performance.now();if(now-lastScrollStamp<6)return;lastScrollStamp=now;state.scrolls++;state.windowScrolls++;state.scrolled=true;state.lastScrollAt=now;state.cancelStreak=0;clearTimeout(state.stallTimer);clearTimeout(state.recoveryTimer);mark('scroll')};d.addEventListener('touchstart',onStart,{passive:true,capture:true});d.addEventListener('touchmove',onMove,{passive:true,capture:true});d.addEventListener('touchend',onEnd,{passive:true,capture:true});d.addEventListener('touchcancel',onTouchCancel,{passive:true,capture:true});d.addEventListener('pointercancel',onPointerCancel,{passive:true,capture:true});d.addEventListener('scroll',onScroll,{passive:true,capture:true});w.addEventListener('scroll',onScroll,{passive:true});w.addEventListener('pagehide',()=>mark('pagehide'),{passive:true});w.addEventListener('pageshow',()=>mark('pageshow'),{passive:true});}catch{}render()}
if(frame){frame.removeAttribute('scrolling');frame.addEventListener('load',()=>{state.loads++;resetPage();requestAnimationFrame(instrument);setTimeout(instrument,180)})}
document.addEventListener('visibilitychange',()=>{mark(document.hidden?'visibility-hidden':'visibility-visible')},{passive:true});window.addEventListener('pageshow',()=>{requestAnimationFrame(instrument)},{passive:true});setInterval(()=>{if(document.getElementById('diagnosticsDialog')?.open)render()},1200);render();